#固定パラメータ
IMAGE_PARAMS = {
    "output_format": "png",
    "aspect_ratio": "16:9",
    "width": 1536,
    "height": 1024,
    "steps": 30,
    "cfg_scale": 7,
    "seed": 123456,
    "style_preset": "fantasy-art",
    "negative_prompt": ", ".join([
        "close-up",
        "portrait",
        "cropped",
        "zoomed in",
        "character too large",
        "off-center composition",
        "blurry",
        "low quality",
        "low resolution",
        "noise",
        "artifacts",
        "extra limbs",
        "bad anatomy",
        "deformed hands",
        "poorly drawn face",
        "oversaturated",
        "flat lighting",
        "cartoon style",
        "anime style",
    ]),
}
