# Generated by Django 6.0.3 on 2026-03-18 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(choices=[('hero', '勇者'), ('warrior', '戦士'), ('wizard', '魔法使い'), ('priest', '僧侶')], max_length=50)),
                ('evolution', models.CharField(blank=True, choices=[('sword_saint', '聖剣ルート'), ('paladin', '聖騎士ルート'), ('spellblade', '魔聖剣ルート')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
