# Generated by Django 6.0.3 on 2026-03-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evolution_prompt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='evolution',
            field=models.CharField(blank=True, choices=[('sword_saint', '聖剣ルート'), ('paladin', '聖騎士ルート'), ('spellblade', '魔聖剣ルート'), ('berserker', '狂戦士ルート'), ('guardisn', '守護戦士ルート'), ('warlord', '戦術化ルート'), ('wizard_archmage', '魔導士ルート'), ('wizard_summoner', '召喚士ルート'), ('wizard_chronomancer', '呪術ルート'), ('high_priest', '狂戦士ルート'), ('cleric_kinght', '守護戦士ルート'), ('bard_priest', '戦術化ルート')], default='', max_length=50),
        ),
    ]
