# Generated by Django 6.0.3 on 2026-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='character_name',
            field=models.CharField(default='未設定', max_length=10, verbose_name='キャラクター名'),
        ),
        migrations.AddField(
            model_name='exp',
            name='user_id',
            field=models.IntegerField(null=True, verbose_name='ユーザーID'),
        ),
    ]
