# Generated by Django 6.0.3 on 2026-03-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_exp_character_name_exp_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EXP',
        ),
    ]
