# Generated by Django 6.0.3 on 2026-03-23 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_character_id_prompts_character_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompts',
            new_name='Prompt',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='character',
            name='create_character',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AlterField(
            model_name='character',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.job'),
        ),
        migrations.AlterUniqueTogether(
            name='prompt',
            unique_together={('character',)},
        ),
    ]
