# Generated by Django 6.0.3 on 2026-03-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_prompts_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='rank',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1),
        ),
    ]
