# Generated by Django 6.0.3 on 2026-03-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_todo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
