# Generated by Django 6.0.3 on 2026-03-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_todo_end_at_todo_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
